#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : ktp-text-ui
Version  : 19.04.1
Release  : 2
URL      : https://download.kde.org/stable/applications/19.04.1/src/ktp-text-ui-19.04.1.tar.xz
Source0  : https://download.kde.org/stable/applications/19.04.1/src/ktp-text-ui-19.04.1.tar.xz
Source99 : https://download.kde.org/stable/applications/19.04.1/src/ktp-text-ui-19.04.1.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0 MIT
Requires: ktp-text-ui-bin = %{version}-%{release}
Requires: ktp-text-ui-data = %{version}-%{release}
Requires: ktp-text-ui-lib = %{version}-%{release}
Requires: ktp-text-ui-license = %{version}-%{release}
Requires: ktp-text-ui-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : knotifyconfig-dev
BuildRequires : kpeople-dev
BuildRequires : ktp-common-internals-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtwebengine-dev
BuildRequires : telepathy-qt-dev

%description
This Adium style is released under MIT/X11 license:
Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

%package bin
Summary: bin components for the ktp-text-ui package.
Group: Binaries
Requires: ktp-text-ui-data = %{version}-%{release}
Requires: ktp-text-ui-license = %{version}-%{release}

%description bin
bin components for the ktp-text-ui package.


%package data
Summary: data components for the ktp-text-ui package.
Group: Data

%description data
data components for the ktp-text-ui package.


%package dev
Summary: dev components for the ktp-text-ui package.
Group: Development
Requires: ktp-text-ui-lib = %{version}-%{release}
Requires: ktp-text-ui-bin = %{version}-%{release}
Requires: ktp-text-ui-data = %{version}-%{release}
Provides: ktp-text-ui-devel = %{version}-%{release}
Requires: ktp-text-ui = %{version}-%{release}
Requires: ktp-text-ui = %{version}-%{release}

%description dev
dev components for the ktp-text-ui package.


%package lib
Summary: lib components for the ktp-text-ui package.
Group: Libraries
Requires: ktp-text-ui-data = %{version}-%{release}
Requires: ktp-text-ui-license = %{version}-%{release}

%description lib
lib components for the ktp-text-ui package.


%package license
Summary: license components for the ktp-text-ui package.
Group: Default

%description license
license components for the ktp-text-ui package.


%package locales
Summary: locales components for the ktp-text-ui package.
Group: Default

%description locales
locales components for the ktp-text-ui package.


%prep
%setup -q -n ktp-text-ui-19.04.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557532918
mkdir -p clr-build
pushd clr-build
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1557532918
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ktp-text-ui
cp COPYING %{buildroot}/usr/share/package-licenses/ktp-text-ui/COPYING
cp LICENSE %{buildroot}/usr/share/package-licenses/ktp-text-ui/LICENSE
cp data/styles/WoshiChat.AdiumMessageStyle/LICENSE %{buildroot}/usr/share/package-licenses/ktp-text-ui/data_styles_WoshiChat.AdiumMessageStyle_LICENSE
pushd clr-build
%make_install
popd
%find_lang kcm_ktp_chat_appearance
%find_lang kcm_ktp_chat_behavior
%find_lang ktp-filters
%find_lang ktp-log-viewer
%find_lang ktpchat
%find_lang ktp-adiumxtra-protocol-handler
%find_lang ktp-text-ui
%find_lang kcm_ktp_chat_messages
%find_lang kcm_ktp_chat_otr

%files
%defattr(-,root,root,-)
/usr/lib64/libexec/ktp-adiumxtra-protocol-handler
/usr/lib64/libexec/ktp-text-ui

%files bin
%defattr(-,root,root,-)
/usr/bin/ktp-log-viewer

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.ktplogviewer.desktop
/usr/share/dbus-1/services/org.freedesktop.Telepathy.Client.KTp.TextUi.service
/usr/share/kservices5/adiumxtra.protocol
/usr/share/kservices5/kcm_ktp_chat_appearance.desktop
/usr/share/kservices5/kcm_ktp_chat_behavior.desktop
/usr/share/kservices5/kcm_ktp_chat_messages.desktop
/usr/share/kservices5/kcm_ktp_chat_otr.desktop
/usr/share/kservices5/kcm_ktp_logviewer_behavior.desktop
/usr/share/kservices5/kcm_ktptextui_message_filter_emoticons.desktop
/usr/share/kservices5/kcm_ktptextui_message_filter_latex.desktop
/usr/share/kservices5/ktptextui_message_filter_bugzilla.desktop
/usr/share/kservices5/ktptextui_message_filter_emoticons.desktop
/usr/share/kservices5/ktptextui_message_filter_formatting.desktop
/usr/share/kservices5/ktptextui_message_filter_geopoint.desktop
/usr/share/kservices5/ktptextui_message_filter_highlight.desktop
/usr/share/kservices5/ktptextui_message_filter_images.desktop
/usr/share/kservices5/ktptextui_message_filter_latex.desktop
/usr/share/kservices5/ktptextui_message_filter_otr.desktop
/usr/share/kservices5/ktptextui_message_filter_searchexpansion.desktop
/usr/share/kservices5/ktptextui_message_filter_tts.desktop
/usr/share/kservices5/ktptextui_message_filter_urlexpansion.desktop
/usr/share/kservices5/ktptextui_message_filter_youtube.desktop
/usr/share/kservicetypes5/ktptxtui_message_filter.desktop
/usr/share/ktelepathy/Template.html
/usr/share/ktelepathy/longurl.js
/usr/share/ktelepathy/longurlServices.json
/usr/share/ktelepathy/showBugzillaInfo.js
/usr/share/ktelepathy/styles/SimKete.AdiumMessageStyle/Contents/Info.plist
/usr/share/ktelepathy/styles/SimKete.AdiumMessageStyle/Contents/Resources/Footer.html
/usr/share/ktelepathy/styles/SimKete.AdiumMessageStyle/Contents/Resources/Header.html
/usr/share/ktelepathy/styles/SimKete.AdiumMessageStyle/Contents/Resources/Incoming/Content.html
/usr/share/ktelepathy/styles/SimKete.AdiumMessageStyle/Contents/Resources/Incoming/NextContent.html
/usr/share/ktelepathy/styles/SimKete.AdiumMessageStyle/Contents/Resources/Incoming/SenderColors.txt
/usr/share/ktelepathy/styles/SimKete.AdiumMessageStyle/Contents/Resources/Outgoing/Content.html
/usr/share/ktelepathy/styles/SimKete.AdiumMessageStyle/Contents/Resources/Outgoing/NextContent.html
/usr/share/ktelepathy/styles/SimKete.AdiumMessageStyle/Contents/Resources/Status.html
/usr/share/ktelepathy/styles/SimKete.AdiumMessageStyle/Contents/Resources/main.css
/usr/share/ktelepathy/styles/WoshiChat.AdiumMessageStyle/Contents/Info.plist
/usr/share/ktelepathy/styles/WoshiChat.AdiumMessageStyle/Contents/Resources/Footer.html
/usr/share/ktelepathy/styles/WoshiChat.AdiumMessageStyle/Contents/Resources/Header.html
/usr/share/ktelepathy/styles/WoshiChat.AdiumMessageStyle/Contents/Resources/Incoming/Content.html
/usr/share/ktelepathy/styles/WoshiChat.AdiumMessageStyle/Contents/Resources/Incoming/NextContent.html
/usr/share/ktelepathy/styles/WoshiChat.AdiumMessageStyle/Contents/Resources/Outgoing/Content.html
/usr/share/ktelepathy/styles/WoshiChat.AdiumMessageStyle/Contents/Resources/Outgoing/NextContent.html
/usr/share/ktelepathy/styles/WoshiChat.AdiumMessageStyle/Contents/Resources/Status.html
/usr/share/ktelepathy/styles/WoshiChat.AdiumMessageStyle/Contents/Resources/Styles/Header.css
/usr/share/ktelepathy/styles/WoshiChat.AdiumMessageStyle/Contents/Resources/Template.html
/usr/share/ktelepathy/styles/WoshiChat.AdiumMessageStyle/Contents/Resources/Topic.html
/usr/share/ktelepathy/styles/WoshiChat.AdiumMessageStyle/Contents/Resources/img/sidebar_header_bg.png
/usr/share/ktelepathy/styles/WoshiChat.AdiumMessageStyle/Contents/Resources/lib/jquery.js
/usr/share/ktelepathy/styles/WoshiChat.AdiumMessageStyle/Contents/Resources/lib/livepipe.js
/usr/share/ktelepathy/styles/WoshiChat.AdiumMessageStyle/Contents/Resources/lib/scrollbar.js
/usr/share/ktelepathy/styles/WoshiChat.AdiumMessageStyle/Contents/Resources/main.css
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Info.plist
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Demo.html
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Footer.html
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Header.html
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Incoming/Content.html
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Incoming/Context.html
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Incoming/NextContent.html
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Incoming/NextContext.html
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Incoming/buddy_icon.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Outgoing/Content.html
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Outgoing/Context.html
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Outgoing/NextContent.html
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Outgoing/NextContext.html
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Outgoing/buddy_icon.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Status.html
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Styles/Header.css
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Styles/Topic.css
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Styles/alternating.css
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Styles/main.css
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Styles/noname.css
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Topic.html
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Blue on Green Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Blue on Green No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Blue on Green No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Blue on Green.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Blue on Red Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Blue on Red No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Blue on Red No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Blue on Red.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Blue on Steel Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Blue on Steel No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Blue on Steel No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Blue on Steel.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Blue on Yellow Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Blue on Yellow No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Blue on Yellow No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Blue on Yellow.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Green on Blue Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Green on Blue No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Green on Blue No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Green on Blue.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Green on Red Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Green on Red No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Green on Red No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Green on Red.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Green on Steel Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Green on Steel No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Green on Steel No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Green on Steel.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Green on Yellow Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Green on Yellow No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Green on Yellow No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Green on Yellow.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Red on Blue Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Red on Blue No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Red on Blue No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Red on Blue.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Red on Green Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Red on Green No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Red on Green No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Red on Green.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Red on Steel Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Red on Steel No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Red on Steel No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Red on Steel.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Red on Yellow Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Red on Yellow No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Red on Yellow No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Red on Yellow.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Steel on Blue Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Steel on Blue No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Steel on Blue No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Steel on Blue.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Steel on Green Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Steel on Green No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Steel on Green No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Steel on Green.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Steel on Red Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Steel on Red No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Steel on Red No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Steel on Red.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Steel on Yellow Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Steel on Yellow No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Steel on Yellow No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Steel on Yellow.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Yellow on Blue Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Yellow on Blue No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Yellow on Blue No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Yellow on Blue.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Yellow on Green Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Yellow on Green No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Yellow on Green No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Yellow on Green.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Yellow on Red Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Yellow on Red No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Yellow on Red No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Yellow on Red.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Yellow on Steel Alternating.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Yellow on Steel No Names Alt.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Yellow on Steel No Names.css"
"/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/Variants/Yellow on Steel.css"
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/DummyContact.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/alert.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/blueBackground.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/blueBackground.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/blueCurves.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/blueCurves.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/blueIndicator.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/blueIndicator.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/blueIndicator2.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/blueIndicatorAlt.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/greenBackground.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/greenBackground.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/greenCurves.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/greenCurves.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/greenIndicator.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/greenIndicator.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/greenIndicator2.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/greenIndicatorAlt.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/redBackground.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/redBackground.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/redCurves.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/redCurves.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/redIndicator.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/redIndicator.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/redIndicator2.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/redIndicatorAlt.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/silverBackground.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/silverCurves.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/steelBackground.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/steelBackground.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/steelCurves.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/steelCurves.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/steelHeading.jpg
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/steelIndicator.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/steelIndicator.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/steelIndicator2.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/steelIndicatorAlt.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/typing-left.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/typing-right.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/yellowBackground.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/yellowBackground.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/yellowCurves.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/yellowCurves.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/yellowHeading.jpg
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/yellowIndicator.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/yellowIndicator.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/yellowIndicator2.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/yellowIndicatorAlt.gif
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/yellowTL.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/images/yellowTR.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/incoming_icon.png
/usr/share/ktelepathy/styles/renkoo.AdiumMessageStyle/Contents/Resources/outgoing_icon.png
/usr/share/ktp-log-viewer/log-viewer.rc
/usr/share/kxmlgui5/ktp-text-ui/chatwindow.rc
/usr/share/telepathy/clients/KTp.TextUi.client

%files dev
%defattr(-,root,root,-)
/usr/lib64/libktpchat.so
/usr/lib64/libktpimagesharer.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/kcm_ktp_chat_appearance.so
/usr/lib64/qt5/plugins/kcm_ktp_chat_behavior.so
/usr/lib64/qt5/plugins/kcm_ktp_chat_messages.so
/usr/lib64/qt5/plugins/kcm_ktp_chat_otr.so
/usr/lib64/qt5/plugins/kcm_ktp_logviewer_behavior.so
/usr/lib64/qt5/plugins/kcm_ktptextui_message_filter_emoticons.so
/usr/lib64/qt5/plugins/kcm_ktptextui_message_filter_latex.so
/usr/lib64/qt5/plugins/ktptextui_message_filter_bugzilla.so
/usr/lib64/qt5/plugins/ktptextui_message_filter_emoticons.so
/usr/lib64/qt5/plugins/ktptextui_message_filter_formatting.so
/usr/lib64/qt5/plugins/ktptextui_message_filter_geopoint.so
/usr/lib64/qt5/plugins/ktptextui_message_filter_highlight.so
/usr/lib64/qt5/plugins/ktptextui_message_filter_images.so
/usr/lib64/qt5/plugins/ktptextui_message_filter_latex.so
/usr/lib64/qt5/plugins/ktptextui_message_filter_otr.so
/usr/lib64/qt5/plugins/ktptextui_message_filter_searchexpansion.so
/usr/lib64/qt5/plugins/ktptextui_message_filter_tts.so
/usr/lib64/qt5/plugins/ktptextui_message_filter_urlexpansion.so
/usr/lib64/qt5/plugins/ktptextui_message_filter_youtube.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ktp-text-ui/COPYING
/usr/share/package-licenses/ktp-text-ui/LICENSE
/usr/share/package-licenses/ktp-text-ui/data_styles_WoshiChat.AdiumMessageStyle_LICENSE

%files locales -f kcm_ktp_chat_appearance.lang -f kcm_ktp_chat_behavior.lang -f ktp-filters.lang -f ktp-log-viewer.lang -f ktpchat.lang -f ktp-adiumxtra-protocol-handler.lang -f ktp-text-ui.lang -f kcm_ktp_chat_messages.lang -f kcm_ktp_chat_otr.lang
%defattr(-,root,root,-)

